<?php

/**
 * Implement hook_ckeditor_plugin()
 * 
 * @return array
 */
function shanti_footnotes_ckeditor_ckeditor_plugin() {
  return array(
    'footnotes' => array(
      'name' => 'footnotes',
      'desc' => t('SHANTI verson of CKEditor Footnotes.'),
      'path' => drupal_get_path('module', 'shanti_footnotes_ckeditor') . '/plugin/',
			'default' => 't',
      'buttons' => array(
        'footnotes' => array(
          'icon' => 'icons/footnotes.png',
          'label' => 'Insert footnote',
        ),
      ),
    ),
  );
}

/**
 * My trying to be wysiwyg compatible
 * 
 * @param string $editor
 * @param string $version
 * @return array
 */
function shanti_footnotes_ckeditor_wysiwyg_plugin($editor, $version) {
  if ($editor == 'ckeditor' && preg_match("/^(4|(4\..*))$/", $version)) {
    return array(
      'footnotes' => array(
        'buttons' => array('footnotes' => t('Add Footnote')),
        'path' => drupal_get_path('module', 'shanti_footnotes_ckeditor') . '/plugin',
        'basePath' => base_path(),
      ),
    );
  }
}